---
title: "centroids_gen_wt"
output: pdf_document
date: "2024-09-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library("vegan")
library("ggplot2")
library("ggrepel")
library("ggpubr")
```

## Distance to centroids 08_wt_vann_wt_gen
```{r, echo=FALSE, fig.width=5, fig.height=5}
plot_boxplots <- function(file_path, samples, group, groups_to_compare, colors, output_file) {
  # Load necessary libraries
  library("vegan")
  library("ggplot2")
  library("ggrepel")
  library("ggpubr")
  
  # Read the distance matrix from the file
  table <- as.dist(read.table(file = file_path,
                              header = TRUE, 
                              row.names = 1,
                              sep = "\t"))
  
  # Filter the distance matrix to include only the samples in 'name'
  table <- as.dist(as.matrix(table)[samples, samples])
  
  
  # Perform betadisper analysis
  group_bdisp <- betadisper(table, group, type = "median")
  group_df <- data.frame(Distance_to_centroid = group_bdisp$distances, Group = group_bdisp$group)
  
  # Generate the boxplot
  boxplot <- ggplot(group_df, aes(x = Group, y = Distance_to_centroid)) +
    geom_boxplot(aes(color = Group), outlier.shape = NA) +
    geom_point(aes(color = Group), size = 2, shape = 21, position = position_jitterdodge()) +
    theme_minimal() +
    theme(legend.position = "none") +  # Remove legend
    ylab(NULL) +  # Remove y-axis title
    labs(title = "", y = "Distance to centroid", x = "") +
    scale_color_manual(values = colors) +
    stat_compare_means(comparisons = groups_to_compare, method = "wilcox.test", digits=4) +
    theme(text = element_text(size = 12), axis.title.y = element_text(size = 12))
  
  # Save the plot as pdf
  ggsave(paste0(output_file, ".pdf"), plot = boxplot, width = 5, height = 5, units = "in")
  
  # Save the plot as TIFF
  ggsave(paste0(output_file, ".tiff"), plot = boxplot, width = 5, height = 5, units = "in", dpi = 300)
  
  return(boxplot)
}

```

### Distance centroids unweighted Gen1 vs wt
```{r, echo=FALSE, fig.width=5, fig.height=5}
samples <- c("IE2", "IE3", "IE5", "IE7", "IE8", "IE9", "IL1", "IL2", "IL3", "IL4", "IL6", "IL8", "1IS", "IS", "P210", "P2-9", "P212", "P2-11", "P24", "P25", "P28", "P2-14")

group <- c("Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "WT", "WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT")

# colors <- c("royalblue", "orangered", "darkviolet", "mediumseagreen")

colors <- c("royalblue", "darkviolet", "mediumseagreen")

groups_to_compare <- list(c("Gen1", "Vannamei WT"),
                          c("Gen1", "WT"),
                          c("WT", "Vannamei WT"))


plot_boxplots("./unweighted_unifrac_dm_wt_vann_gen.txt", samples, group, groups_to_compare, colors, "./unweighted_wt_gen1")
```

### Distance centroids unweighted Gen1 vs wt merged
```{r, echo=FALSE, fig.width=5, fig.height=5}
samples <- c("IE2", "IE3", "IE5", "IE7", "IE8", "IE9", "IL1", "IL2", "IL3", "IL4", "IL6", "IL8", "1IS", "IS", "P210", "P2-9", "P212", "P2-11", "P24", "P25", "P28", "P2-14")

group <- c("Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Gen1", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT")

# colors <- c("royalblue", "orangered", "darkviolet", "mediumseagreen")

colors <- c("royalblue", "darkviolet", "mediumseagreen")

groups_to_compare <- list(c("Gen1", "Vannamei WT"))


plot_boxplots("./unweighted_unifrac_dm_wt_vann_gen.txt", samples, group, groups_to_compare, colors, "./unweighted_wt_gen1_merged")
```


### Distance centroids unweighted Gen2 vs wt
```{r, echo=FALSE, fig.width=5, fig.height=5}
samples <- c("IA2", "IA3", "IA4", "IA5", "IA7", "IA8", "IA9", "1IS", "IS", "P210", "P2-9", "P212", "P2-11", "P24", "P25", "P28", "P2-14")

group <- c("Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "WT", "WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT")

groups_to_compare <- list(c("Gen2", "Vannamei WT"),
                          c("Gen2", "WT"),
                          c("WT", "Vannamei WT"))

colors <- c("orangered", "darkviolet", "mediumseagreen")

plot_boxplots("./unweighted_unifrac_dm_wt_vann_gen.txt", samples, group, groups_to_compare, colors, "./unweighted_wt_gen2")
```

### Distance centroids unweighted Gen2 vs wt merged
```{r, echo=FALSE, fig.width=5, fig.height=5}
samples <- c("IA2", "IA3", "IA4", "IA5", "IA7", "IA8", "IA9", "1IS", "IS", "P210", "P2-9", "P212", "P2-11", "P24", "P25", "P28", "P2-14")

group <- c("Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "Gen2", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT", "Vannamei WT")

groups_to_compare <- list(c("Gen2", "Vannamei WT"))

colors <- c("orangered", "darkviolet", "mediumseagreen")

plot_boxplots("./unweighted_unifrac_dm_wt_vann_gen.txt", samples, group, groups_to_compare, colors, "./unweighted_wt_gen2_merged")
```