---
title: "boxplots_probiotics_genetics_v3"
output: pdf_document
date: "2024-09-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library("optparse")
library("ggplot2")
library("reshape")
require("gridExtra")
library("ggpubr")
library("ggh4x")
library("dplyr")
library("rstatix")
library("vegan")
```

## Boxplots probiotics gut
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Boxplot function definition
generate_probiotics_boxplot <- function(data_file, comparison, groups_to_compare, y_axis, colors, output_file) {
  # Load necessary libraries
  library("ggplot2")
  library("ggpubr")
  library("dplyr")
  
  # Read the data
  data <- read.table(file = data_file, sep = "\t", header = TRUE)
  
  data$group <- factor(data$group, levels = unique(data$group))
  
  # Define colors
  colors <- colors
  
  # Create the boxplot
  probiotics_boxplot <- ggplot(data, aes(x = group, y = !!sym(comparison))) +
    geom_boxplot(aes(color = group), outlier.shape = NA) +
    geom_point(aes(color = group), size = 2, shape = 21, position = position_jitterdodge()) +
    theme_test() +
    theme(legend.position = "none") +
    labs(x = "", y = y_axis) +
    scale_color_manual(values = colors) +
    theme(text = element_text(size = 12), axis.title.y = element_text(size = 12)) +
    stat_compare_means(comparisons = groups_to_compare, method = "wilcox.test", digits=4)
  
  # Save the plot as pdf
  ggsave(paste0(output_file, ".pdf"), plot = probiotics_boxplot, width = 5, height = 5, units = "in")
  
  # Save the plot as TIFF
  ggsave(paste0(output_file, ".tiff"), plot = probiotics_boxplot, width = 5, height = 5, units = "in", dpi = 300)

  # Show the plot
  return(probiotics_boxplot)
}

generate_probiotics_boxplot_log <- function(data_file, comparison, groups_to_compare, y_axis, colors,  output_file) {
  # Load necessary libraries
  library("ggplot2")
  library("ggpubr")
  library("dplyr")
  
  # Read the data
  data <- read.table(file = data_file, sep = "\t", header = TRUE)
  
  data$group <- factor(data$group, levels = unique(data$group))
  
  # Define colors
  colors <- colors
  
  # Create the boxplot
  probiotics_boxplot <- ggplot(data,
                               aes(x = group,
                                   y = log10(!!sym(comparison)))) +
    geom_boxplot(aes(color = group), outlier.shape = NA) +
    geom_point(aes(color = group), size = 2, shape = 21, position = position_jitterdodge()) +
    theme_test() +
    theme(legend.position = "none") +
    labs(x = "", y = y_axis) +
    scale_color_manual(values = colors) +
    theme(text = element_text(size = 12), axis.title.y = element_text(size = 12)) +
    stat_compare_means(comparisons = groups_to_compare, method = "wilcox.test", digits=4)
  
  # Save the plot as pdf
  ggsave(paste0(output_file, ".pdf"), plot = probiotics_boxplot, width = 5, height = 5, units = "in")
  
  # Save the plot as TIFF
  ggsave(paste0(output_file, ".tiff"), plot = probiotics_boxplot, width = 5, height = 5, units = "in", dpi = 300)

  # Show the plot
  return(probiotics_boxplot)
}

```

### Genus gut 
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut probiotics genus
generate_probiotics_boxplot(data_file = "./gut_genus_probiotics_v3.tsv", 
                            comparison = "relab_gut_genus",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./genus_gut_probiotics_v3")
```

### Genus gut log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut probiotics genus log10
generate_probiotics_boxplot_log(data_file = "./gut_genus_probiotics_v3.tsv", 
                            comparison = "relab_gut_genus",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./log_genus_gut_probiotics_v3")
```

### Species gut
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut probiotics species
generate_probiotics_boxplot(data_file = "./gut_species_probiotics_v3.tsv", 
                            comparison = "relab_gut_species",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./species_gut_probiotics_v3")
```

### Species gut log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut probiotics species
generate_probiotics_boxplot_log(data_file = "./gut_species_probiotics_v3.tsv",
                            comparison = "relab_gut_species",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./log_species_gut_probiotics_v3")
```

### Genus hep 
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Hep probiotics genus
generate_probiotics_boxplot(data_file = "./hep_genus_probiotics_v3.tsv", 
                            comparison = "relab_hep_genus",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./genus_hep_probiotics_v3")
```

### Genus hep log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Hep probiotics genus log10
generate_probiotics_boxplot_log(data_file = "./hep_genus_probiotics_v3.tsv",
                            comparison = "relab_hep_genus",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./log_genus_hep_probiotics_v3")
```

### Species hep
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Hep probiotics species
generate_probiotics_boxplot(data_file = "./hep_species_probiotics_v3.tsv", 
                            comparison = "relab_hep_species",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./species_hep_probiotics_v3")
```

### Species hep log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Hep probiotics species
generate_probiotics_boxplot_log(data_file = "./hep_species_probiotics_v3.tsv",
                            comparison = "relab_hep_species",
                            groups_to_compare = list(c("Gen1", "Gen2")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("royalblue", "orangered"),
                            output_file = "./log_species_hep_probiotics_v3")
```

### Genus gut wt 
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut wt probiotics genus
generate_probiotics_boxplot(data_file = "./wt_genus_probiotics_v3.tsv", 
                            comparison = "relab_gut_genus",
                            groups_to_compare = list(c("Healthy", "Disease")),
                            y_axis = "Relative abundance",
                            colors <- c("darkviolet", "mediumseagreen"),
                            output_file = "./genus_wt_probiotics_v3")
```

### Genus gut wt log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut wt probiotics genus log10
generate_probiotics_boxplot_log(data_file = "./wt_genus_probiotics_v3.tsv",
                            comparison = "relab_gut_genus",
                            groups_to_compare = list(c("Healthy", "Disease")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("darkviolet", "mediumseagreen"),
                            output_file = "./log_genus_wt_probiotics_v3")
```

### Species gut wt 
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut wt probiotics species
generate_probiotics_boxplot(data_file = "./wt_species_probiotics_v3.tsv", 
                            comparison = "relab_gut_species",
                            groups_to_compare = list(c("Healthy", "Disease")),
                            y_axis = "Relative abundance",
                            colors <- c("darkviolet", "mediumseagreen"),
                            output_file = "./species_wt_probiotics_v3")
```

### Species gut wt log10
```{r, echo=FALSE, fig.width=5, fig.height=5}
# Gut wt probiotics species log10
generate_probiotics_boxplot_log(data_file = "./wt_species_probiotics_v3.tsv",
                            comparison = "relab_gut_species",
                            groups_to_compare = list(c("Healthy", "Disease")),
                            y_axis = "Relative abundance (log10)",
                            colors <- c("darkviolet", "mediumseagreen"),
                            output_file = "./log_species_wt_probiotics_v3")
```
